[workspace]

resolver = "2"

members = ["tests", "reflected", "reflected_proc"]

default-members = ["reflected"]

[workspace.dependencies]
chrono = "0.4"
rand = "0.8"
rust_decimal = "1.34"

reflected_proc = { path = "reflected_proc" }
# reflected_proc = "0.9.1"
